[package]
name = "kentauri"
version = "0.1.0"
authors = ["9uapaw <gyorandr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4.2"
lazy_static = "1.4.0"
ustr = "0.2.1"
